apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: streamlit-kafka-app:latest
        imagePullPolicy: Never
        args: ["python", "producer.py"]
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKER
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TOPIC
        - name: DEVICE_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEVICE_ID
        - name: REFRESH_RATE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REFRESH_RATE
        - name: PYTHONUNBUFFERED
          value: "1"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "ps -ef | grep python | grep producer"
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Always
