apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-dashboard
  namespace: kafka-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-dashboard
  template:
    metadata:
      labels:
        app: streamlit-dashboard
    spec:
      containers:
      - name: streamlit-dashboard
        image: streamlit-kafka-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKER
        - name: TOPIC
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: TOPIC
        - name: PYTHONUNBUFFERED
          value: "1"
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: kafka-demo
spec:
  selector:
    app: streamlit-dashboard
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
  type: NodePort
